### ISSUE TITLE
code pas très propre

### ISSUE THREAD

**Issue by giovanne3u** [torzuoliH/cisiie_atelier2#65]
Roux ton code est dégueulasse, tu pouvais pas coder comme on a appris en cours avec des belles factoryes, en définissant les méthodes dedans ?

**Comment by vivienLarriere** [comment]
Je suis perdu dans le flow du code. Help je me noie dans le scope.

**Comment by giovanne3u** [comment]
@Kixot oui c'est de toi qu'on parle

**Comment by Grenadator** [comment]
Juste parce que l'intéressé est roux, je like lel

**Comment by giovanne3u** [comment]
@Grenadator sale putaclic

**Comment by Grenadator** [comment]
Vive le Grand Sharkz qui nous a apprit comment insulter ses mates avec propreté sur des tickets

**Comment by Kixot** [comment]
Le truc c'est qu'on a aucune méthode à définir dedans puisque ngResource le fait de base. Si tu savais lire la documentation (https://docs.angularjs.org/api/ngResource/service/$resource) tu ne serais pas venu pleurer.

**Comment by MickaelBaye** [comment]
N'importe quoi... *facepalm*
